import React from 'react';
import { ShapFactor } from '../types';
import { Info, ArrowUpRight, ArrowDownRight, Layers } from 'lucide-react';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, ReferenceLine, Cell } from 'recharts';

interface ShapExplanationProps {
  factors: ShapFactor[] | null;
  baseValue?: number | null;
}

export const ShapExplanationChart: React.FC<ShapExplanationProps> = ({
  factors,
  baseValue = null,
}) => {
  const isPending = !factors || factors.length === 0;

  return (
    <div className="bg-slate-900/60 border border-slate-800 rounded-xl p-5 space-y-6">
      
      {/* Section Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-800/80 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <Layers className="w-4 h-4 text-emerald-400" />
            <h3 className="text-base font-semibold text-slate-100">
              Explainable AI (SHAP) Feature Attribution
            </h3>
          </div>
          <p className="text-xs text-slate-400 mt-0.5">
            Marginal contribution of campaign parameters towards success probability
          </p>
        </div>
        <div className="text-[11px] font-mono px-2.5 py-1 bg-slate-950 border border-slate-800 text-slate-400 rounded-lg">
          Formula: f(x) = E[f(X)] + &sum; &phi;<sub>i</sub>
        </div>
      </div>

      {isPending ? (
        /* Clean Stage 1 Empty State */
        <div className="space-y-6">
          <div className="p-5 bg-slate-950/70 border border-slate-800/80 rounded-xl flex items-start gap-3.5">
            <div className="p-2 bg-amber-950/50 text-amber-400 rounded-lg border border-amber-800/60 shrink-0 mt-0.5">
              <Info className="w-4 h-4" />
            </div>
            <div className="space-y-1.5 text-xs">
              <h4 className="text-sm font-semibold text-slate-100">
                SHAP explanations unavailable
              </h4>
              <p className="text-slate-400 leading-relaxed">
                Feature contributions will appear here once the prediction is generated by the ML pipeline.
              </p>
              <p className="text-[11px] text-slate-400 leading-relaxed pt-1 border-t border-slate-800/80">
                In accordance with final-year academic rigor, Shapley feature attribution values (&phi;<sub>i</sub>) are calculated strictly by Python's <code>shap.TreeExplainer</code> or <code>shap.KernelExplainer</code> over trained model weights. No synthetic or simulated values are generated.
              </p>
            </div>
          </div>

          {/* Structured Schema Prototype Table showing examiners how real SHAP values will map */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <span className="text-xs font-semibold uppercase tracking-wider text-slate-400">
                Expected SHAP Attribution Table Schema
              </span>
              <span className="text-[11px] text-amber-400/90 font-medium">
                [Awaiting SHAP Model Output]
              </span>
            </div>

            <div className="overflow-x-auto border border-slate-800 rounded-lg">
              <table className="w-full text-xs text-left">
                <thead className="bg-slate-950 text-slate-400 border-b border-slate-800">
                  <tr>
                    <th className="py-2.5 px-4 font-medium">Campaign Feature</th>
                    <th className="py-2.5 px-4 font-medium">SHAP Impact (&phi;)</th>
                    <th className="py-2.5 px-4 font-medium">Direction</th>
                    <th className="py-2.5 px-4 font-medium">Relative Importance</th>
                    <th className="py-2.5 px-4 font-medium">Pipeline Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800/60 font-mono text-slate-400">
                  <tr>
                    <td className="py-3 px-4 font-sans font-medium text-slate-300">Campaign Duration (days)</td>
                    <td className="py-3 px-4 text-slate-400">—</td>
                    <td className="py-3 px-4 text-slate-400">Pending</td>
                    <td className="py-3 px-4 text-slate-400">Uncalibrated</td>
                    <td className="py-3 px-4 text-amber-400/90 font-sans">Awaiting TreeExplainer</td>
                  </tr>
                  <tr>
                    <td className="py-3 px-4 font-sans font-medium text-slate-300">Funding Goal ($)</td>
                    <td className="py-3 px-4 text-slate-400">—</td>
                    <td className="py-3 px-4 text-slate-400">Pending</td>
                    <td className="py-3 px-4 text-slate-400">Uncalibrated</td>
                    <td className="py-3 px-4 text-amber-400/90 font-sans">Awaiting TreeExplainer</td>
                  </tr>
                  <tr>
                    <td className="py-3 px-4 font-sans font-medium text-slate-300">Creator Experience Level</td>
                    <td className="py-3 px-4 text-slate-400">—</td>
                    <td className="py-3 px-4 text-slate-400">Pending</td>
                    <td className="py-3 px-4 text-slate-400">Uncalibrated</td>
                    <td className="py-3 px-4 text-amber-400/90 font-sans">Awaiting TreeExplainer</td>
                  </tr>
                  <tr>
                    <td className="py-3 px-4 font-sans font-medium text-slate-300">Category Baseline Index</td>
                    <td className="py-3 px-4 text-slate-400">—</td>
                    <td className="py-3 px-4 text-slate-400">Pending</td>
                    <td className="py-3 px-4 text-slate-400">Uncalibrated</td>
                    <td className="py-3 px-4 text-amber-400/90 font-sans">Awaiting TreeExplainer</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      ) : (
        /* Real SHAP Visualization when ML pipeline returns factors */
        <div className="space-y-6">
          <div className="h-64 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart
                data={factors}
                layout="vertical"
                margin={{ top: 5, right: 30, left: 100, bottom: 5 }}
              >
                <XAxis type="number" stroke="#64748b" fontSize={11} />
                <YAxis dataKey="feature" type="category" stroke="#94a3b8" fontSize={11} />
                <Tooltip
                  contentStyle={{ backgroundColor: '#020617', borderColor: '#334155', fontSize: '12px' }}
                />
                <ReferenceLine x={0} stroke="#475569" />
                <Bar dataKey="impact">
                  {factors.map((entry, index) => (
                    <Cell
                      key={`cell-${index}`}
                      fill={entry.direction === 'Positive' ? '#10b981' : '#f43f5e'}
                    />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>

          <div className="overflow-x-auto border border-slate-800 rounded-lg">
            <table className="w-full text-xs text-left">
              <thead className="bg-slate-950 text-slate-400 border-b border-slate-800">
                <tr>
                  <th className="py-2.5 px-4">Feature</th>
                  <th className="py-2.5 px-4">SHAP Value</th>
                  <th className="py-2.5 px-4">Direction</th>
                  <th className="py-2.5 px-4">Importance</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800 font-mono">
                {factors.map((f, i) => (
                  <tr key={i}>
                    <td className="py-2.5 px-4 font-sans text-slate-200">{f.feature}</td>
                    <td className={`py-2.5 px-4 ${f.impact >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
                      {f.impact > 0 ? `+${f.impact.toFixed(4)}` : f.impact.toFixed(4)}
                    </td>
                    <td className="py-2.5 px-4">
                      <span className="inline-flex items-center gap-1 font-sans">
                        {f.direction === 'Positive' ? (
                          <>
                            <ArrowUpRight className="w-3.5 h-3.5 text-emerald-400" />
                            <span className="text-emerald-400">Positive</span>
                          </>
                        ) : (
                          <>
                            <ArrowDownRight className="w-3.5 h-3.5 text-rose-400" />
                            <span className="text-rose-400">Negative</span>
                          </>
                        )}
                      </span>
                    </td>
                    <td className="py-2.5 px-4 text-slate-300 font-sans">{f.importance}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

    </div>
  );
};
